tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init:
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscli.zip
      unzip awscli.zip
      sudo ./aws/install
vscode:
  extensions:
    - 42Crunch.vscode-openapi
